# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CarDetectUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from tkinter import StringVar, Entry, Tk
from tkinter.filedialog import askopenfilename

import cv2
import numpy as np
from PIL import Image, ImageTk
from tensorflow import keras
from core import locate_and_correct
from Unet import unet_predict
from CNN import cnn_predict

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.win = Tk()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 755)
        font = QtGui.QFont()
        font.setPointSize(17)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CarWidget = QtWidgets.QWidget(self.centralwidget)
        self.CarWidget.setGeometry(QtCore.QRect(10, 200, 512, 512))
        self.CarWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.CarWidget.setObjectName("CarWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 160, 121, 41))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(710, 80, 245, 85))
        self.widget1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget1.setObjectName("widget1")
        self.widget_pre1 = QtWidgets.QWidget(self.centralwidget)
        self.widget_pre1.setGeometry(QtCore.QRect(710, 190, 245, 85))
        self.widget_pre1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget_pre1.setObjectName("widget_pre1")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(560, 300, 131, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.widget_pre2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_pre2.setGeometry(QtCore.QRect(710, 410, 245, 85))
        self.widget_pre2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget_pre2.setObjectName("widget_pre2")
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(710, 300, 245, 85))
        self.widget2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget2.setObjectName("widget2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(560, 520, 131, 191))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.widget_pre3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_pre3.setGeometry(QtCore.QRect(710, 630, 245, 85))
        self.widget_pre3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget_pre3.setObjectName("widget_pre3")
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(710, 520, 245, 85))
        self.widget3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"")
        self.widget3.setObjectName("widget3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(560, 80, 131, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 401, 111))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.widget1.raise_()
        self.widget_pre1.raise_()
        self.layoutWidget.raise_()
        self.widget_pre2.raise_()
        self.widget2.raise_()
        self.layoutWidget_2.raise_()
        self.widget_pre3.raise_()
        self.widget3.raise_()
        self.CarWidget.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.unet = keras.models.load_model('unet.h5')
        self.cnn = keras.models.load_model('cnn.h5')
        print('正在启动中,请稍等...')
        cnn_predict(self.cnn, [np.zeros((80, 240, 3))])
        print("已启动,开始识别吧！")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "原图片"))
        self.label_4.setText(_translate("MainWindow", "车牌区域1："))
        self.label_5.setText(_translate("MainWindow", "识别结果1："))
        self.label_6.setText(_translate("MainWindow", "车牌区域1："))
        self.label_7.setText(_translate("MainWindow", "识别结果1："))
        self.label_2.setText(_translate("MainWindow", "车牌区域1："))
        self.label_3.setText(_translate("MainWindow", "识别结果1："))
        self.pushButton.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_2.setText(_translate("MainWindow", "开始识别"))
        self.pushButton_3.setText(_translate("MainWindow", "清除所有"))



    def closeEvent():  # 关闭前清除session(),防止'NoneType' object is not callable
        keras.backend.clear_session()
        sys.exit()

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)



app = QtWidgets.QApplication(sys.argv)

window = MainWindow()
window.show()
app.exec()